# Generated by Django 3.1 on 2024-10-18 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
